CREATE TABLE IF NOT EXISTS "foundation_users_user" (
	"removed" BOOLEAN NOT NULL DEFAULT FALSE,
	"creator" INT8 NOT NULL DEFAULT -1,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"modifier" INT8 NOT NULL DEFAULT -1,
	"modified_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"id" INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"version" INT4 NOT NULL DEFAULT 0,
	"profile" JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS "foundation_users_certificate" (
	"removed" BOOLEAN NOT NULL DEFAULT FALSE,
	"creator" INT8 NOT NULL DEFAULT -1,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"modifier" INT8 NOT NULL DEFAULT -1,
	"modified_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"id" INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"version" INT4 NOT NULL DEFAULT 0,
	"history" JSONB,
	"user" INT8 NOT NULL,
	"kind" INT4 NOT NULL,
	"identifier" TEXT NOT NULL,
	"certificate" JSONB NOT NULL,
	"profile" JSONB NOT NULL);
CREATE INDEX "idx_foundation_users_certificate-user" ON "foundation_users_certificate" ("user");
ALTER TABLE "foundation_users_certificate" ADD CONSTRAINT "udx_foundation_users_certificate-identifier_kind" UNIQUE ("identifier", "kind");
