CREATE TABLE IF NOT EXISTS "foundation_audits_audit" (
	"removed" BOOLEAN NOT NULL DEFAULT FALSE,
	"creator" INT8 NOT NULL DEFAULT -1,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"modifier" INT8 NOT NULL DEFAULT -1,
	"modified_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"id" INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"version" INT4 NOT NULL DEFAULT 0,
	"history" JSONB,
	"topic" TEXT NOT NULL,
	"request" JSONB,
	"response" JSONB,
	"status" INT4 NOT NULL,
	"actor" INT8 NOT NULL,
	"reported" INT8 NOT NULL,
	"audited" INT8 NOT NULL,
	"auditor" INT8 NOT NULL,
	"result" INT4 NOT NULL,
	"comment" TEXT NOT NULL);
CREATE INDEX "idx_foundation_audits_audit-result" ON "foundation_audits_audit" ("result");
CREATE INDEX "idx_foundation_audits_audit-topic" ON "foundation_audits_audit" ("topic");
CREATE INDEX "idx_foundation_audits_audit-status" ON "foundation_audits_audit" ("status");
